CREATE TABLE USERS (
    ID char(16) NOT NULL,
    NAME varchar(31) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    EMAIL varchar(31) NOT NULL,
    PERMISSION_SCOPE int(255) DEFAULT 5,
    LAST_EDITED DATETIME NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE TASKS (
    TASK_ID char(16) NOT NULL,
    USER_ID char(16) NOT NULL,
    TASK_NAME varchar(31) NOT NULL,
    TASK_INFO Text NOT NULL,
    TASK_SUBJECT varchar(31) NOT NULL,
    TASK_TIME int(64),
    TASK_IMPORTANCE INT(1) NOT NULL,
    TASK_TYPE ENUM("personal", "timed") NOT NULL,

    PRIMARY KEY(TASK_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE SHORTCUTS (
    SHORTCUT_ID char(16) NOT NULL,
    USER_ID char(16) NOT NULL,
    LINK varchar(31) NOT NULL,
    PICTURE_URL varchar(31) NOT NULL,

    PRIMARY KEY(SHORTCUT_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE AUTH (
    KEY_NO char(16) NOT NULL,
    USER_ID char(16) NOT NULL,
    PERMISSIONS int(255) NOT NULL,
    UNTIL_DATE DATETIME NOT NULL,
    PRIMARY KEY(KEY_NO, USER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)  
);

