CREATE TABLE SHORTCUTS (
    SHORTCUT_ID char(16) NOT NULL,
    USER_ID char(16) NOT NULL,
    LINK varchar(31) NOT NULL,
    PICTURE_URL varchar(31) NOT NULL,

    PRIMARY KEY(SHORTCUT_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
)