CREATE TABLE TASKS (
    TASK_ID char(16) NOT NULL,
    USER_ID char(16) NOT NULL,
    TASK_NAME varchar(31) NOT NULL,
    TASK_INFO Text NOT NULL,
    TASK_SUBJECT varchar(31) NOT NULL,
    TASK_TIME int(64),
    TASK_IMPORTANCE INT(1) NOT NULL,
    TASK_TYPE ENUM("personal", "timed") NOT NULL,

    PRIMARY KEY(TASK_ID, ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
)