CREATE TABLE USERS (
    ID char(16) NOT NULL,
    NAME varchar(31) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    EMAIL varchar(31) NOT NULL,
    PERMISSION_SCOPE int(255) DEFAULT 5,
    LAST_EDITED DATETIME NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    PRIMARY KEY(ID)
)