CREATE TABLE USERS (
    ID char(16) NOT NULL,
    NAME varchar(31) NOT NULL,
    PASSWORD varchar(254) NOT NULL,
    EMAIL varchar(31) NOT NULL,
    LAST_EDITED DATETIME NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    PRIMARY KEY(ID)
)